
path: '/content/gdrive/My Drive/fire_data/data' # dataset root dir
train: train/images # train images (relative to 'path')
val: train/images  # val images (relative to 'path')

# Classes
names:
  0: fire
